# coding: utf-8

"""
    Torizon IDE-backend API

    Toradex API to build and deploy applications running as containers on Torizon  # noqa: E501

    The version of the OpenAPI document: 1.0.14
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from moses_client.configuration import Configuration


class InlineResponse200(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'host_ip': 'str',
        'host_port': 'str'
    }

    attribute_map = {
        'host_ip': 'HostIp',
        'host_port': 'HostPort'
    }

    def __init__(self, host_ip=None, host_port=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._host_ip = None
        self._host_port = None
        self.discriminator = None

        if host_ip is not None:
            self.host_ip = host_ip
        if host_port is not None:
            self.host_port = host_port

    @property
    def host_ip(self):
        """Gets the host_ip of this InlineResponse200.  # noqa: E501

        The IP address for local container instance  # noqa: E501

        :return: The host_ip of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._host_ip

    @host_ip.setter
    def host_ip(self, host_ip):
        """Sets the host_ip of this InlineResponse200.

        The IP address for local container instance  # noqa: E501

        :param host_ip: The host_ip of this InlineResponse200.  # noqa: E501
        :type host_ip: str
        """

        self._host_ip = host_ip

    @property
    def host_port(self):
        """Gets the host_port of this InlineResponse200.  # noqa: E501

        port used for SSH  # noqa: E501

        :return: The host_port of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._host_port

    @host_port.setter
    def host_port(self, host_port):
        """Sets the host_port of this InlineResponse200.

        port used for SSH  # noqa: E501

        :param host_port: The host_port of this InlineResponse200.  # noqa: E501
        :type host_port: str
        """

        self._host_port = host_port

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200):
            return True

        return self.to_dict() != other.to_dict()
