/**
 * Torizon Deployment API
 * Toradex Development API to build and deploy application on Torizon
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Application {
    /**
    * Unique id
    */
    'id'?: string;
    /**
    * id of the platform used to generate this application configuration
    */
    'platformid'?: string;
    /**
    * folder where application configuration and extra files are stored
    */
    'folder'?: string;
    'props'?: { [key: string]: { [key: string]: string; }; };
    'dockercomposefile'?: { [key: string]: string; };
    'startupscript'?: { [key: string]: string; };
    'shutdownscript'?: { [key: string]: string; };
    'ports'?: { [key: string]: { [key: string]: string; }; };
    'volumes'?: { [key: string]: { [key: string]: string; }; };
    'devices'?: { [key: string]: Array<string>; };
    'networks'?: { [key: string]: Array<string>; };
    'extraparms'?: { [key: string]: { [key: string]: object; }; };
    'username'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "platformid",
            "baseName": "platformid",
            "type": "string"
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "string"
        },
        {
            "name": "props",
            "baseName": "props",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "dockercomposefile",
            "baseName": "dockercomposefile",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "startupscript",
            "baseName": "startupscript",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "shutdownscript",
            "baseName": "shutdownscript",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "volumes",
            "baseName": "volumes",
            "type": "{ [key: string]: { [key: string]: string; }; }"
        },
        {
            "name": "devices",
            "baseName": "devices",
            "type": "{ [key: string]: Array<string>; }"
        },
        {
            "name": "networks",
            "baseName": "networks",
            "type": "{ [key: string]: Array<string>; }"
        },
        {
            "name": "extraparms",
            "baseName": "extraparms",
            "type": "{ [key: string]: { [key: string]: object; }; }"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Application.attributeTypeMap;
    }
}

