/**
 * Torizon Deployment API
 * Toradex Development API to build and deploy application on Torizon
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DockerAddress } from './dockerAddress';
import { DockerEndpointSettings } from './dockerEndpointSettings';
import { DockerPortBinding } from './dockerPortBinding';

/**
* NetworkSettings exposes the network settings in the API
*/
export class DockerNetworkSettings {
    /**
    * Name of the network\'a bridge (for example, `docker0`).
    */
    'bridge'?: string;
    /**
    * SandboxID uniquely represents a container\'s network stack.
    */
    'sandboxID'?: string;
    /**
    * Indicates if hairpin NAT should be enabled on the virtual interface. 
    */
    'hairpinMode'?: boolean;
    /**
    * IPv6 unicast address using the link-local prefix.
    */
    'linkLocalIPv6Address'?: string;
    /**
    * Prefix length of the IPv6 unicast address.
    */
    'linkLocalIPv6PrefixLen'?: number;
    /**
    * PortMap describes the mapping of container ports to host ports, using the container\'s port-number and protocol as key in the format `<port>/<protocol>`, for example, `80/udp`.  If a container\'s port is mapped for multiple protocols, separate entries are added to the mapping table. 
    */
    'ports'?: { [key: string]: Array<DockerPortBinding>; };
    /**
    * SandboxKey identifies the sandbox
    */
    'sandboxKey'?: string;
    /**
    * 
    */
    'secondaryIPAddresses'?: Array<DockerAddress>;
    /**
    * 
    */
    'secondaryIPv6Addresses'?: Array<DockerAddress>;
    /**
    * EndpointID uniquely represents a service endpoint in a Sandbox.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'endpointID'?: string;
    /**
    * Gateway address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'gateway'?: string;
    /**
    * Global IPv6 address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'globalIPv6Address'?: string;
    /**
    * Mask length of the global IPv6 address.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'globalIPv6PrefixLen'?: number;
    /**
    * IPv4 address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'iPAddress'?: string;
    /**
    * Mask length of the IPv4 address.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'iPPrefixLen'?: number;
    /**
    * IPv6 gateway address for this network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'iPv6Gateway'?: string;
    /**
    * MAC address for the container on the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0 
    */
    'macAddress'?: string;
    /**
    * Information about all networks that the container is connected to. 
    */
    'networks'?: { [key: string]: DockerEndpointSettings; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bridge",
            "baseName": "Bridge",
            "type": "string"
        },
        {
            "name": "sandboxID",
            "baseName": "SandboxID",
            "type": "string"
        },
        {
            "name": "hairpinMode",
            "baseName": "HairpinMode",
            "type": "boolean"
        },
        {
            "name": "linkLocalIPv6Address",
            "baseName": "LinkLocalIPv6Address",
            "type": "string"
        },
        {
            "name": "linkLocalIPv6PrefixLen",
            "baseName": "LinkLocalIPv6PrefixLen",
            "type": "number"
        },
        {
            "name": "ports",
            "baseName": "Ports",
            "type": "{ [key: string]: Array<DockerPortBinding>; }"
        },
        {
            "name": "sandboxKey",
            "baseName": "SandboxKey",
            "type": "string"
        },
        {
            "name": "secondaryIPAddresses",
            "baseName": "SecondaryIPAddresses",
            "type": "Array<DockerAddress>"
        },
        {
            "name": "secondaryIPv6Addresses",
            "baseName": "SecondaryIPv6Addresses",
            "type": "Array<DockerAddress>"
        },
        {
            "name": "endpointID",
            "baseName": "EndpointID",
            "type": "string"
        },
        {
            "name": "gateway",
            "baseName": "Gateway",
            "type": "string"
        },
        {
            "name": "globalIPv6Address",
            "baseName": "GlobalIPv6Address",
            "type": "string"
        },
        {
            "name": "globalIPv6PrefixLen",
            "baseName": "GlobalIPv6PrefixLen",
            "type": "number"
        },
        {
            "name": "iPAddress",
            "baseName": "IPAddress",
            "type": "string"
        },
        {
            "name": "iPPrefixLen",
            "baseName": "IPPrefixLen",
            "type": "number"
        },
        {
            "name": "iPv6Gateway",
            "baseName": "IPv6Gateway",
            "type": "string"
        },
        {
            "name": "macAddress",
            "baseName": "MacAddress",
            "type": "string"
        },
        {
            "name": "networks",
            "baseName": "Networks",
            "type": "{ [key: string]: DockerEndpointSettings; }"
        }    ];

    static getAttributeTypeMap() {
        return DockerNetworkSettings.attributeTypeMap;
    }
}

