/**
 * Torizon IDE-backend API
 * Toradex API to build and deploy applications running as containers on Torizon
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* A mount point inside a container
*/
export class DockerMountPoint {
    'type'?: string;
    'name'?: string;
    'source'?: string;
    'destination'?: string;
    'driver'?: string;
    'mode'?: string;
    'rW'?: boolean;
    'propagation'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "Type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "Source",
            "type": "string"
        },
        {
            "name": "destination",
            "baseName": "Destination",
            "type": "string"
        },
        {
            "name": "driver",
            "baseName": "Driver",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "Mode",
            "type": "string"
        },
        {
            "name": "rW",
            "baseName": "RW",
            "type": "boolean"
        },
        {
            "name": "propagation",
            "baseName": "Propagation",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DockerMountPoint.attributeTypeMap;
    }
}

