/**
 * Torizon IDE-backend API
 * Toradex API to build and deploy applications running as containers on Torizon
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MemInfo {
    /**
    * total memory in kb
    */
    'total'?: number;
    /**
    * available memory in kb
    */
    'available'?: number;
    /**
    * free memory in kb
    */
    'free'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "available",
            "baseName": "available",
            "type": "number"
        },
        {
            "name": "free",
            "baseName": "free",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MemInfo.attributeTypeMap;
    }
}

